[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "layouts/_shortcodes"
target = "layouts/shortcodes"

[[module.mounts]]
source = "static"
target = "static"
