name = "Vault"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "https://www.disgone.com/"
tags = []
features = []
min_version = "0.32.2"

[author]
    name = "Shaun Smith"
    homepage = "https://www.disgone.com/"
